# Generated by Django 3.1.7 on 2021-03-27 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_article_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='is_active',
        ),
    ]
