# Generated by Django 3.1.7 on 2021-03-29 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_article_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='media', verbose_name='Картинки для статьи '),
        ),
    ]
