# Generated by Django 3.1.7 on 2021-03-31 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_article_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_activate',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='author',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
