# Generated by Django 3.1.7 on 2021-04-11 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20210331_2105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='is_activate',
            new_name='is_active',
        ),
    ]
